import Foundation
import OhMyUsageApplication

typealias UsageMetricTotals = OhMyUsageApplication.UsageMetricTotals
typealias UsageAnalyticsFilterMode = OhMyUsageApplication.UsageAnalyticsFilterMode
typealias UsageAnalyticsRange = OhMyUsageApplication.UsageAnalyticsRange
typealias UsageAnalyticsFilter = OhMyUsageApplication.UsageAnalyticsFilter
typealias UsageAnalyticsRecordSource = OhMyUsageApplication.UsageAnalyticsRecordSource
typealias UsageAnalyticsRecord = OhMyUsageApplication.UsageAnalyticsRecord
typealias UsageAnalyticsBreakdownItem = OhMyUsageApplication.UsageAnalyticsBreakdownItem
typealias UsageTrendBucket = OhMyUsageApplication.UsageTrendBucket
typealias UsageProviderCategoryStats = OhMyUsageApplication.UsageProviderCategoryStats
typealias UsageProviderStats = OhMyUsageApplication.UsageProviderStats
typealias UsageModelStats = OhMyUsageApplication.UsageModelStats
typealias UsageAnalyticsModelOption = OhMyUsageApplication.UsageAnalyticsModelOption
typealias UsageAnalyticsSnapshot = OhMyUsageApplication.UsageAnalyticsSnapshot
typealias UsageAnalyticsFileFingerprint = OhMyUsageApplication.UsageAnalyticsFileFingerprint
typealias UsageAnalyticsSourceFingerprint = OhMyUsageApplication.UsageAnalyticsSourceFingerprint
typealias UsageAnalyticsCacheEntry = OhMyUsageApplication.UsageAnalyticsCacheEntry
